### PR TITLE
Remove isDirty check on user model

### LINKED ISSUE #53: SupportKit.updateUser doesn't work
We at [razorpay](https://razorpay.com) are relying on `SupportKit.updateUser` for adding email and contact info. But this doesn't seem to work since last release.

`SupportKit.user.set('email', 'foo@bar.com')` followed by `SupportKit.user.save()` is working though, and we're falling back to it for now.

### PR DESCRIPTION
**Pull request by lemieux**
This should fix #53. That check is removed for now, but it should be back when we reintroduce throttling.

@jpjoyal @alavers @juliangarritano

### CODE REVIEW

File: src/js/controllers/chatController.js [hunk 1]
```diff
@@ -79,14 +79,17 @@ module.exports = ViewController.extend({
         conversationDeferred.then(function(conversation) {
             // update the user before sending the message to ensure properties are correct
             this.user.save({}, {
-                wait: true
+                wait: true,
+                parse: true
```
Comment (alavers) [inline src/js/controllers/chatController.js]: Is this option necessary?

**Comment by alavers** [comment]
:+1:

File: src/js/controllers/chatController.js (hunk 1 above)
Comment (lemieux) [inline src/js/controllers/chatController.js]: good point, not sure we need it on that one. We have a custom parse function, because the server sometimes returns only the id.
